on:
  rss:
    url:
      - https://www.drupal.org/changes/drupal/rss.xml

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo "title: ${{on.rss.outputs.title}}"
          echo "link: ${{on.rss.outputs.link}}"
          echo "pubDate: ${{on.rss.outputs.pubDate}}"
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DRUPAL }}
          DISCORD_EMBEDS: '[
              {
                "author": {
                  "name": "Drupal Change Records"
                },
                "title": "${{on.rss.outputs.title}}",
                "url": "${{on.rss.outputs.link}}",
                "footer": {
                  "text": "${{on.rss.outputs.pubDate}}"
                }
              }
            ]'
