on:
  rss:
    url:
      - https://www.drupal.org/node/3060/release/feed

jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DRUPAL_RELEASES }}
          DISCORD_EMBEDS: '[
              {
                "title": "${{on.rss.outputs.title}}",
                "url": "${{on.rss.outputs.link}}",
                "description": "${{on.rss.outputs.description}}"
              }
            ]'
